language: node_js
node_js:
- "8"
env:
  global:
    secure: raPghfPxc16gOWuTA9SqYYJ1OVB7TjFEjiAd0hSBV4UvMylxeTByRZWIViEtNi4EbKFDCoyA4SJw9SNt9nbNPgaPq1wWuX7ThDHWhWdXaUj+7nSn3HrQ6sN7evAOzz1Rdn21vAubUBAcAbZJTx8SAERWOvDyMvBZSQxCqfqdCO0iBPZTWak8F2/3CCiudK7AB32l6SdHuYpYB27b1BuELZfx7pg2KBnR3iGO7QAYdsmYDiXj7rfQpVvfqBumCRPrzOA/epkOfJtVI1tDWA6hoMeD5MdAmfWMiZMfDhliaTzCl/r4P7oqNEeopR8debgiaGlPu5YpehkLgIRlb6pF9Wm6iaprIYlLlOFKTi7iQOv56/QmOqS/dWa4ZCTbOC3Rz50ovqKUMylxcZ6WFZyLQfh1GzzZ/Zh2OngOI3IAfx5Dij4j9KK2dZLWjRiNLMAaLjXJx6cNBTeiawi6r38zRsZz4tf6GBZFeHHE/X1hLETovjeu0v54xTrbuP4FjCD730FbYkiRJWlEcDgZxwCHO64fiCa2m7TmYZgyvlasLulu9T6ym8QFOAdtBbpqPZzlJgj+2bbcuTXsTJ6huBFNjRcgtcz/YtEWyf5peaqWukGlRSmrZSP7McVP3qx2sAh/J/4Kr6LxSYuKqg90FhMJppB13Y66eZpSZwvAcAigbuM=
script:
- npm test
after_success:
- npm run coveralls
